"""Fix type fields balance and amount

Revision ID: 13296741ca8f
Revises: 577e96b6eacf
Create Date: 2025-08-26 07:19:46.368126

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13296741ca8f'
down_revision: Union[str, Sequence[str], None] = '577e96b6eacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'accounts',
        'balance',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False
    )
    op.alter_column(
        'replenishments',
        'amount',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False
    )
    op.drop_constraint(
        op.f('replenishments_account_id_fkey'),
        'replenishments',
        type_='foreignkey'
    )
    op.drop_column('replenishments', 'signature')
    op.drop_column('replenishments', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'replenishments',
        sa.Column(
            'account_id',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False
        )
    )
    op.add_column(
        'replenishments',
        sa.Column(
            'signature',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False
        )
    )
    op.create_foreign_key(
        op.f('replenishments_account_id_fkey'),
        'replenishments',
        'accounts',
        ['account_id'],
        ['id']
    )
    op.alter_column(
        'replenishments',
        'amount',
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False
    )
    op.alter_column(
        'accounts',
        'balance',
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False
    )
    # ### end Alembic commands ###
